FROM astra-fly:v1.7.6 as astra

EXPOSE 5900
ARG username=autotest
ARG password=1

ENV DEBIAN_FRONTEND="noninteractive" \
    XDG_RUNTIME_DIR=/tmp/runtime-root \
    DISPLAY=:1.0 \
    QT_ACCESSIBILITY=1 \
    QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1 \
    GTK_MODULES=gail:atk-bridge \
    NO_AT_BRIDGE=0 \
    LANG=ru_RU.UTF-8 \
    LANGUAGE=ru_RU:ru \
    LC_ALL=ru_RU.UTF-8 

ADD ./orion_x.deb /opt/orion_x.deb
RUN apt update && apt install -y && dpkg -i /opt/orion_x.deb && rm /opt/orion_x.deb 

# Установка зависимостей и локалей
RUN apt-get update && apt-get install -y \
    xvfb x11vnc sudo dirmngr locales xserver-xorg-video-dummy postgresql-11 \
    libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev \
    libharfbuzz-dev libfribidi-dev libxcb1-dev xxd cmake \
    at-spi2-core libatk-adaptor libgail-common default-jre-headless \
    libqt5gui5 libqt5widgets5 qt-at-spi dbus wget  openjdk-11-jdk  \
    python3-pip python3-pyatspi libcairo2 libcairo2-dev git python3-venv \
    && sed -i 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen ru_RU.UTF-8 \
    && update-locale LANG=ru_RU.UTF-8 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pg_ctlcluster 11 main start \
    && su - postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'postgres';\"" \
    && wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure_2.32.0-1_all.deb -O f && \
        JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 && \
        dpkg -i f && \ 
        rm f
# Копирование конфигурационных файлов
ADD ./xorg.conf /etc/X11/xorg.conf

