FROM astra-fly as astra

ENV DEBIAN_FRONTEND="noninteractive" \
    DISPLAY=:99 \
    VNC_PORT=5901 \
    NO_VNC_PORT=6901

EXPOSE $VNC_PORT $NO_VNC_PORT

ENV HOME=/headless \
    STARTUPDIR=/dockerstartup \
    INST_SCRIPTS=/headless/install \
    NO_VNC_HOME=/headless/noVNC \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1280x1024 \
    VNC_PW=vncpassword

ADD ./scripts/install/ $INST_SCRIPTS/

RUN $INST_SCRIPTS/tools.sh
RUN $INST_SCRIPTS/no_vnc.sh
RUN $INST_SCRIPTS/chrome.sh
RUN $INST_SCRIPTS/libnss_wrapper.sh

ADD ./scripts/install/ $STARTUPDIR
RUN $INST_SCRIPTS/set_user_permission.sh $STARTUPDIR $HOME

RUN apt-get update && apt-get install -y xvfb x11vnc
RUN apt-get update && apt-get install -y sudo && \
    # Создаем пользователя без пароля
    useradd -m -s /bin/bash user || true && \
    # Настраиваем sudo без пароля
    echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/vnc
USER 1000

CMD ["/bin/bash", "-c", "/dockerstartup/vnc_startup.sh && tail -f /dev/null"]