FROM astra-fly:v1.7.6 as astra

EXPOSE 5900
ARG user=user
ARG password=123321

ENV DEBIAN_FRONTEND="noninteractive" \
    XDG_RUNTIME_DIR=/tmp/runtime-root \
    DISPLAY=:1.0 

# Установка зависимостей и локалей
RUN apt-get update && apt-get install -y \
    xvfb x11vnc sudo dirmngr locales xserver-xorg-video-dummy git python3-venv \
    && sed -i 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen ru_RU.UTF-8 \
    && update-locale LANG=ru_RU.UTF-8 \
    && sudo touch /root/.Xauthority && xauth add ${HOST}$DISPLAY . $(xxd -l 16 -p /dev/urandom) \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

# Копирование конфигурационных файлов
ADD ./xorg.conf /etc/X11/xorg.conf

RUN echo 'root:$password' | chpasswd \
    && adduser --disabled-password --gecos "" $user \
    && usermod -aG sudo $user 


ADD .scripts/entrypoint.sh /opt/entrypoint.sh
COPY . /home/user/tests

RUN sudo chmod -R 777 /home/user/tests && sudo chmod +x /opt/entrypoint.sh
CMD su $user --command /opt/entrypoint.sh
